### ISSUE TITLE
Flag location configuration

### ISSUE THREAD

**Issue by mgerst** [mgerst/flag-slurper#2]
AutoPWN currently attempts to look for anything in /root that either has the `.flag` extension or is roughly the right file size for a flag. I'd like to keep this, but also add the ability to specify the flag location on a per-service basis. We should be able to tell AutoPWN what directory the flag should be in as well as what the expected name and/or format is. Possibly something like this:

```yaml
flags:
  - service: Web HTTP
    type: blue
    location: /root
    name: team{num}_www_root.flag
    search: yes
```
