### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by mgerst** [mgerst/flag-slurper#4]
Add a "project" system that allows for configuring flag slurper per CDC. For instance #2 could be in the project configuration. It would also tell flag-slurper where to find the `teams.yml`, `services.yml`, and `results.yml` files.

Example configuration:
```yaml
---
project: ISU2-18
version: "1.0"
base: ~/cdcs/isu2-2018
flags: [...]
results: results.yml
teams: teams.yml
services: services.yml
```
